/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ResellerSalesPrice struct {
	ObjectId int32 `json:"objectId,omitempty"`
	ObjectType *ResellerSalesPriceObjectType `json:"objectType,omitempty"`
	Type_ *ResellerSalesPriceType `json:"type,omitempty"`
	PriceType *ResellerSalesPricePriceType `json:"priceType,omitempty"`
	Value float64 `json:"value,omitempty"`
	FromDate time.Time `json:"fromDate,omitempty"`
	ChangedBy string `json:"changedBy,omitempty"`
}
