/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Asset struct {
	Id int32 `json:"id,omitempty"`
	Status *AssetStatus `json:"status,omitempty"`
	ExternalOrderId string `json:"externalOrderId,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	ExternalProductId string `json:"externalProductId,omitempty"`
	ExternalSkuId string `json:"externalSkuId,omitempty"`
	Name string `json:"name,omitempty"`
	StartDate time.Time `json:"startDate,omitempty"`
	ExpirationDate time.Time `json:"expirationDate,omitempty"`
	ResellerCustomerId int32 `json:"resellerCustomerId,omitempty"`
	Scope *AssetScope `json:"scope,omitempty"`
	AssetType *AssetType `json:"assetType,omitempty"`
	BillingCycle *BillingCycleType `json:"billingCycle,omitempty"`
	PublisherId int32 `json:"publisherId,omitempty"`
	ProgramId int32 `json:"programId,omitempty"`
	ReservationId string `json:"reservationId,omitempty"`
	ReservationUsedInSubscriptionId int32 `json:"reservationUsedInSubscriptionId,omitempty"`
	ReservationUsedInSubscription *SubscriptionLite `json:"reservationUsedInSubscription,omitempty"`
	PurchaseCurrency string `json:"purchaseCurrency,omitempty"`
	PurchasePrice float64 `json:"purchasePrice,omitempty"`
	SalesCurrency string `json:"salesCurrency,omitempty"`
	SalesPrice float64 `json:"salesPrice,omitempty"`
	CreatedDate time.Time `json:"createdDate,omitempty"`
	ModifiedDate time.Time `json:"modifiedDate,omitempty"`
	ChangedBy string `json:"changedBy,omitempty"`
	ResellerPriceType *SalesPriceType `json:"resellerPriceType,omitempty"`
	ResellerPriceTypeValue float64 `json:"resellerPriceTypeValue,omitempty"`
	ReservedInstanceArtifactResourceId string `json:"reservedInstanceArtifactResourceId,omitempty"`
	PurchaseDate time.Time `json:"purchaseDate,omitempty"`
	InvoiceProfile *ObjectReference `json:"invoiceProfile,omitempty"`
	Tags *AssetTags `json:"tags,omitempty"`
}
