/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Token struct {
	AccessToken string `json:"accessToken,omitempty"`
	IdentityToken string `json:"identityToken,omitempty"`
	Error_ string `json:"error,omitempty"`
	ExpiresIn int64 `json:"expiresIn,omitempty"`
	TokenType string `json:"tokenType,omitempty"`
	RefreshToken string `json:"refreshToken,omitempty"`
}
