/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BillingCycleType int32

// List of BillingCycleType
const (
	0__BillingCycleType BillingCycleType = "0"
	1__BillingCycleType BillingCycleType = "1"
	2__BillingCycleType BillingCycleType = "2"
	3__BillingCycleType BillingCycleType = "3"
	4__BillingCycleType BillingCycleType = "4"
	5__BillingCycleType BillingCycleType = "5"
)
