/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AssetScope int32

// List of AssetScope
const (
	1__AssetScope AssetScope = "1"
	2__AssetScope AssetScope = "2"
)
