/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AgreementStatus int32

// List of AgreementStatus
const (
	0__AgreementStatus AgreementStatus = "0"
	1__AgreementStatus AgreementStatus = "1"
	2__AgreementStatus AgreementStatus = "2"
	3__AgreementStatus AgreementStatus = "3"
)
