/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductInformation struct {
	ExternalProductId int32 `json:"externalProductId,omitempty"`
	CultureCode string `json:"cultureCode,omitempty"`
	Description string `json:"description,omitempty"`
	LearnMoreLink string `json:"learnMoreLink,omitempty"`
}
