/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AssetSortBy int32

// List of AssetSortBy
const (
	0__AssetSortBy AssetSortBy = "0"
	1__AssetSortBy AssetSortBy = "1"
	2__AssetSortBy AssetSortBy = "2"
)
