/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerTenantAddress struct {
	FirstName string `json:"firstName,omitempty"`
	MiddleName string `json:"middleName,omitempty"`
	LastName string `json:"lastName,omitempty"`
	AddressLine1 string `json:"addressLine1,omitempty"`
	AddressLine2 string `json:"addressLine2,omitempty"`
	AddressLine3 string `json:"addressLine3,omitempty"`
	City string `json:"city,omitempty"`
	Region string `json:"region,omitempty"`
	PostalCode string `json:"postalCode,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	CountryName string `json:"countryName,omitempty"`
}
