/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type FacebookOrder struct {
	ContactName string `json:"contactName,omitempty"`
	ContactEmail string `json:"contactEmail,omitempty"`
	ConsumerContactName string `json:"consumerContactName,omitempty"`
	ConsumerFullLegalName string `json:"consumerFullLegalName,omitempty"`
	ConsumerContactEmail string `json:"consumerContactEmail,omitempty"`
	OrganizationId int32 `json:"organizationId,omitempty"`
	InvoiceProfileId int32 `json:"invoiceProfileId,omitempty"`
	SubscriptionStartDate time.Time `json:"subscriptionStartDate,omitempty"`
	ConsumerSignupEmail string `json:"consumerSignupEmail,omitempty"`
}
