/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SortOrder int32

// List of SortOrder
const (
	0__SortOrder SortOrder = "0"
	1__SortOrder SortOrder = "1"
)
