/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type GoogleOrder struct {
	ContactName string `json:"contactName,omitempty"`
	ContactEmail string `json:"contactEmail,omitempty"`
	ConsumerContactName string `json:"consumerContactName,omitempty"`
	ConsumerFullLegalName string `json:"consumerFullLegalName,omitempty"`
	ConsumerContactEmail string `json:"consumerContactEmail,omitempty"`
	OrganizationId int32 `json:"organizationId,omitempty"`
	InvoiceProfileId int32 `json:"invoiceProfileId,omitempty"`
	SubscriptionStartDate time.Time `json:"subscriptionStartDate,omitempty"`
	DomainName string `json:"domainName,omitempty"`
	ConsumerCountry string `json:"consumerCountry,omitempty"`
	ConsumerStreetAddress string `json:"consumerStreetAddress,omitempty"`
	ConsumerCity string `json:"consumerCity,omitempty"`
	ConsumerState string `json:"consumerState,omitempty"`
	ConsumerZipCode string `json:"consumerZipCode,omitempty"`
	ConsumerPhoneNumber string `json:"consumerPhoneNumber,omitempty"`
	PrimaryAdminName string `json:"primaryAdminName,omitempty"`
	PrimaryAdminUserName string `json:"primaryAdminUserName,omitempty"`
}
