/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AzureSubscriptionAssignAdmin struct {
	AzurePlanId int32 `json:"azurePlanId,omitempty"`
	AzureSubscriptionId int32 `json:"azureSubscriptionId,omitempty"`
	AdminEmail string `json:"adminEmail,omitempty"`
}
