/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductTypeDto int32

// List of ProductTypeDto
const (
	0__ProductTypeDto ProductTypeDto = "0"
	1__ProductTypeDto ProductTypeDto = "1"
	2__ProductTypeDto ProductTypeDto = "2"
	3__ProductTypeDto ProductTypeDto = "3"
)
