/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PriceCalculationType int32

// List of PriceCalculationType
const (
	0__PriceCalculationType PriceCalculationType = "0"
	1__PriceCalculationType PriceCalculationType = "1"
	2__PriceCalculationType PriceCalculationType = "2"
	3__PriceCalculationType PriceCalculationType = "3"
	4__PriceCalculationType PriceCalculationType = "4"
)
