/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AgreementTypeConsent int32

// List of AgreementTypeConsent
const (
	0__AgreementTypeConsent AgreementTypeConsent = "0"
	1__AgreementTypeConsent AgreementTypeConsent = "1"
)
