/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AgreementProductsSubFilter struct {
	PartNumbers []string `json:"partNumbers,omitempty"`
	PublisherIds []int32 `json:"publisherIds,omitempty"`
	PublisherNames []string `json:"publisherNames,omitempty"`
	PoolNames []string `json:"poolNames,omitempty"`
	OperatingSystemNames []string `json:"operatingSystemNames,omitempty"`
	LevelNames []string `json:"levelNames,omitempty"`
	LanguageNames []string `json:"languageNames,omitempty"`
	LicenseAgreementTypeNames []string `json:"licenseAgreementTypeNames,omitempty"`
	LicenseTypeNames []string `json:"licenseTypeNames,omitempty"`
	ProductFamilyNames []string `json:"productFamilyNames,omitempty"`
	ProductTypeNames []string `json:"productTypeNames,omitempty"`
	ProgramNames []string `json:"programNames,omitempty"`
	OfferingNames []string `json:"offeringNames,omitempty"`
	PurchasePeriodNames []string `json:"purchasePeriodNames,omitempty"`
	PurchaseUnitNames []string `json:"purchaseUnitNames,omitempty"`
	VersionNames []string `json:"versionNames,omitempty"`
	RegionNames []string `json:"regionNames,omitempty"`
	ProductCategoryNames []string `json:"productCategoryNames,omitempty"`
	CatalogNames []string `json:"catalogNames,omitempty"`
	BillingCycles []string `json:"billingCycles,omitempty"`
}
