/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProvisionType int32

// List of ProvisionType
const (
	0__ProvisionType ProvisionType = "0"
	1__ProvisionType ProvisionType = "1"
	2__ProvisionType ProvisionType = "2"
	3__ProvisionType ProvisionType = "3"
	4__ProvisionType ProvisionType = "4"
	5__ProvisionType ProvisionType = "5"
)
