/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AzurePlan struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	PublisherSubscriptionId string `json:"publisherSubscriptionId,omitempty"`
	Status *SubscriptionStatus `json:"status,omitempty"`
	RegisteredForReservedInstance bool `json:"registeredForReservedInstance,omitempty"`
	Organization *ObjectReference `json:"organization,omitempty"`
	CustomerTenant *CustomerTenantReference `json:"customerTenant,omitempty"`
}
