/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type SubscriptionAddOn struct {
	Id int32 `json:"id,omitempty"`
	PublisherSubscriptionId string `json:"publisherSubscriptionId,omitempty"`
	PublisherCustomerId string `json:"publisherCustomerId,omitempty"`
	Name string `json:"name,omitempty"`
	Status *SubscriptionStatus `json:"status,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	Organization *ObjectReference `json:"organization,omitempty"`
	OrderId string `json:"orderId,omitempty"`
	CreationDate time.Time `json:"creationDate,omitempty"`
	Product *ProductReference `json:"product,omitempty"`
	Publisher *ObjectReference `json:"publisher,omitempty"`
	Markup float64 `json:"markup,omitempty"`
	SubscriptionTags *SubscriptionTags `json:"subscriptionTags,omitempty"`
	TermDuration string `json:"termDuration,omitempty"`
	AutoRenewEnabled bool `json:"autoRenewEnabled,omitempty"`
	CancellationAllowedUntilDate time.Time `json:"cancellationAllowedUntilDate,omitempty"`
}
