/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductContainerCommentType int32

// List of ProductContainerCommentType
const (
	0__ProductContainerCommentType ProductContainerCommentType = "0"
	1__ProductContainerCommentType ProductContainerCommentType = "1"
	2__ProductContainerCommentType ProductContainerCommentType = "2"
	4__ProductContainerCommentType ProductContainerCommentType = "4"
	8__ProductContainerCommentType ProductContainerCommentType = "8"
	16__ProductContainerCommentType ProductContainerCommentType = "16"
	32__ProductContainerCommentType ProductContainerCommentType = "32"
	64__ProductContainerCommentType ProductContainerCommentType = "64"
	128__ProductContainerCommentType ProductContainerCommentType = "128"
	256__ProductContainerCommentType ProductContainerCommentType = "256"
	512__ProductContainerCommentType ProductContainerCommentType = "512"
	1024__ProductContainerCommentType ProductContainerCommentType = "1024"
	2048__ProductContainerCommentType ProductContainerCommentType = "2048"
	4096__ProductContainerCommentType ProductContainerCommentType = "4096"
	8190__ProductContainerCommentType ProductContainerCommentType = "8190"
)
