/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SubscriptionStatus int32

// List of SubscriptionStatus
const (
	0__SubscriptionStatus SubscriptionStatus = "0"
	1__SubscriptionStatus SubscriptionStatus = "1"
	2__SubscriptionStatus SubscriptionStatus = "2"
	4__SubscriptionStatus SubscriptionStatus = "4"
	8__SubscriptionStatus SubscriptionStatus = "8"
	16__SubscriptionStatus SubscriptionStatus = "16"
	30__SubscriptionStatus SubscriptionStatus = "30"
	31__SubscriptionStatus SubscriptionStatus = "31"
	32__SubscriptionStatus SubscriptionStatus = "32"
	64__SubscriptionStatus SubscriptionStatus = "64"
)
