/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SalesPriceType int32

// List of SalesPriceType
const (
	0__SalesPriceType SalesPriceType = "0"
	1__SalesPriceType SalesPriceType = "1"
	2__SalesPriceType SalesPriceType = "2"
	3__SalesPriceType SalesPriceType = "3"
	1__SalesPriceType SalesPriceType = "-1"
)
