/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type User struct {
	Id string `json:"id,omitempty"`
	UserName string `json:"userName,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	LastName string `json:"lastName,omitempty"`
	Email string `json:"email,omitempty"`
	EmailConfirmed bool `json:"emailConfirmed,omitempty"`
	LockoutEnabled bool `json:"lockoutEnabled,omitempty"`
	LockoutEnd time.Time `json:"lockoutEnd,omitempty"`
	PhoneNumber string `json:"phoneNumber,omitempty"`
	PhoneNumberConfirmed bool `json:"phoneNumberConfirmed,omitempty"`
	TwoFactorEnabled bool `json:"twoFactorEnabled,omitempty"`
	TenantAdmin bool `json:"tenantAdmin,omitempty"`
}
