/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerTenantDetailed struct {
	Tenant *CustomerTenant `json:"tenant,omitempty"`
	User *CustomerTenantUser `json:"user,omitempty"`
	Profile *CustomerTenantProfile `json:"profile,omitempty"`
	Company *CustomerTenantCompany `json:"company,omitempty"`
}
