/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductContainerCategory int32

// List of ProductContainerCategory
const (
	0__ProductContainerCategory ProductContainerCategory = "0"
	1__ProductContainerCategory ProductContainerCategory = "1"
	2__ProductContainerCategory ProductContainerCategory = "2"
)
