/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SubscriptionConversion struct {
	BillingCycle *BillingCycleEnum `json:"billingCycle,omitempty"`
	OfferId string `json:"offerId,omitempty"`
	OrderId string `json:"orderId,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	TargetOfferId string `json:"targetOfferId,omitempty"`
	ProductName string `json:"productName,omitempty"`
}
