/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OrganizationAccessRole int32

// List of OrganizationAccessRole
const (
	0__OrganizationAccessRole OrganizationAccessRole = "0"
	1__OrganizationAccessRole OrganizationAccessRole = "1"
	2__OrganizationAccessRole OrganizationAccessRole = "2"
	3__OrganizationAccessRole OrganizationAccessRole = "3"
	4__OrganizationAccessRole OrganizationAccessRole = "4"
	7__OrganizationAccessRole OrganizationAccessRole = "7"
)
