/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResellerSalesPriceType int32

// List of ResellerSalesPriceType
const (
	1__ResellerSalesPriceType ResellerSalesPriceType = "1"
	2__ResellerSalesPriceType ResellerSalesPriceType = "2"
	3__ResellerSalesPriceType ResellerSalesPriceType = "3"
)
