/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductContainerType int32

// List of ProductContainerType
const (
	0__ProductContainerType ProductContainerType = "0"
	1__ProductContainerType ProductContainerType = "1"
	2__ProductContainerType ProductContainerType = "2"
	4__ProductContainerType ProductContainerType = "4"
	8__ProductContainerType ProductContainerType = "8"
	16__ProductContainerType ProductContainerType = "16"
)
