/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type BlogItem struct {
	Title string `json:"title,omitempty"`
	Author string `json:"author,omitempty"`
	Description string `json:"description,omitempty"`
	Image string `json:"image,omitempty"`
	Link string `json:"link,omitempty"`
	PublicationDate time.Time `json:"publicationDate,omitempty"`
}
