/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CategoryUsageCost struct {
	Subcategory string `json:"subcategory,omitempty"`
	Amount float64 `json:"amount,omitempty"`
	CurrencyCode string `json:"currencyCode,omitempty"`
}
