/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerTenantType int32

// List of CustomerTenantType
const (
	0__CustomerTenantType CustomerTenantType = "0"
	1__CustomerTenantType CustomerTenantType = "1"
	2__CustomerTenantType CustomerTenantType = "2"
)
