/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AzureSubscriptionTags struct {
	CostCenter string `json:"costCenter,omitempty"`
	Department string `json:"department,omitempty"`
	Project string `json:"project,omitempty"`
	Custom string `json:"custom,omitempty"`
	Owner string `json:"owner,omitempty"`
}
