/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type GroupedBillingStatement struct {
	GroupId int32 `json:"groupId,omitempty"`
	Id int32 `json:"id,omitempty"`
	TotalSalesPrice *Price `json:"totalSalesPrice,omitempty"`
	InvoiceProfile *ObjectReference `json:"invoiceProfile,omitempty"`
	Organization *ObjectReference `json:"organization,omitempty"`
	StartDate time.Time `json:"startDate,omitempty"`
	EndDate time.Time `json:"endDate,omitempty"`
	ProvisionType *ProvisionType `json:"provisionType,omitempty"`
	OrderId string `json:"orderId,omitempty"`
}
