/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Organization struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	ParentId int32 `json:"parentId,omitempty"`
	CrayonCompanyName string `json:"crayonCompanyName,omitempty"`
	AccountNumber string `json:"accountNumber,omitempty"`
}
