/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActivationLink struct {
	SubscriptionId string `json:"subscriptionId,omitempty"`
	Uri string `json:"uri,omitempty"`
}
