/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ManagementLink struct {
	Link string `json:"link,omitempty"`
	ResellerCustomer *ObjectReference `json:"resellerCustomer,omitempty"`
	Subscription *ObjectReference `json:"subscription,omitempty"`
	Text string `json:"text,omitempty"`
}
