/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type SubcategoryUsageCostRequest struct {
	ResellerCustomerId int32 `json:"resellerCustomerId,omitempty"`
	SubscriptionId string `json:"subscriptionId,omitempty"`
	Category string `json:"category,omitempty"`
	Subcategory string `json:"subcategory,omitempty"`
	CurrencyCode string `json:"currencyCode,omitempty"`
	From time.Time `json:"from,omitempty"`
	To time.Time `json:"to,omitempty"`
}
