/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ChangeTypeEnum int32

// List of ChangeTypeEnum
const (
	1__ChangeTypeEnum ChangeTypeEnum = "1"
	2__ChangeTypeEnum ChangeTypeEnum = "2"
	3__ChangeTypeEnum ChangeTypeEnum = "3"
)
