/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ProductVariant struct {
	Id int32 `json:"id,omitempty"`
	Product *ProductReference `json:"product,omitempty"`
	PartNumber string `json:"partNumber,omitempty"`
	ProductName string `json:"productName,omitempty"`
	Publisher *ObjectReference `json:"publisher,omitempty"`
	Program *ObjectReference `json:"program,omitempty"`
	ProductFamily *ObjectReference `json:"productFamily,omitempty"`
	Language *ObjectReference `json:"language,omitempty"`
	Level *ObjectReference `json:"level,omitempty"`
	ProductType *ObjectReference `json:"productType,omitempty"`
	Pool *ObjectReference `json:"pool,omitempty"`
	LicenseType *ObjectReference `json:"licenseType,omitempty"`
	LicenseAgreementType *ObjectReference `json:"licenseAgreementType,omitempty"`
	OperatingSystem *ObjectReference `json:"operatingSystem,omitempty"`
	Offering *ObjectReference `json:"offering,omitempty"`
	MinimumCommitment *MinimumCommitmentLight `json:"minimumCommitment,omitempty"`
	UnitCount int32 `json:"unitCount,omitempty"`
	Version string `json:"version,omitempty"`
	PurchaseUnit string `json:"purchaseUnit,omitempty"`
	PurchasePeriod string `json:"purchasePeriod,omitempty"`
	AddDate time.Time `json:"addDate,omitempty"`
	DeleteDate time.Time `json:"deleteDate,omitempty"`
	ProductCategory string `json:"productCategory,omitempty"`
	Region string `json:"region,omitempty"`
	IsTrial bool `json:"isTrial,omitempty"`
	DefaultBillingCycleId int32 `json:"defaultBillingCycleId,omitempty"`
	AvailableBillingCycleIds []int32 `json:"availableBillingCycleIds,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	MinimumQuantity float64 `json:"minimumQuantity,omitempty"`
	MaximumQuantity float64 `json:"maximumQuantity,omitempty"`
}
