/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductRowPatch struct {
	Id int32 `json:"id,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	Comment string `json:"comment,omitempty"`
	UsageCountryCode string `json:"usageCountryCode,omitempty"`
	UserId string `json:"userId,omitempty"`
	Agreement *ObjectReference `json:"agreement,omitempty"`
	ProductVariant *ObjectReference `json:"productVariant,omitempty"`
	Grouping *ObjectReference `json:"grouping,omitempty"`
}
