/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type SubscriptionTags struct {
	SubscriptionId int32 `json:"subscriptionId,omitempty"`
	CostCenter string `json:"costCenter,omitempty"`
	Department string `json:"department,omitempty"`
	Project string `json:"project,omitempty"`
	Custom string `json:"custom,omitempty"`
	Owner string `json:"owner,omitempty"`
	CreatedDate time.Time `json:"createdDate,omitempty"`
	ModifiedDate time.Time `json:"modifiedDate,omitempty"`
}
