/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AssetOrder struct {
	ExternalOrderId string `json:"externalOrderId,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	ResellerCustomerId int32 `json:"resellerCustomerId,omitempty"`
	AdminAccount string `json:"adminAccount,omitempty"`
	NotificationEmail string `json:"notificationEmail,omitempty"`
	InvoiceProfileId int32 `json:"invoiceProfileId,omitempty"`
	Errors []AssetOrderError `json:"errors,omitempty"`
	OrderLines []AssetOrderLine `json:"orderLines,omitempty"`
}
