/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SubscriptionTransitionEligibility struct {
	CatalogItemId string `json:"catalogItemId,omitempty"`
	Title string `json:"title,omitempty"`
	Description string `json:"description,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	Eligibilities []SubscriptionTransitionEligibilityDetail `json:"eligibilities,omitempty"`
}
