/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResellerSalesPriceObjectType int32

// List of ResellerSalesPriceObjectType
const (
	1__ResellerSalesPriceObjectType ResellerSalesPriceObjectType = "1"
	2__ResellerSalesPriceObjectType ResellerSalesPriceObjectType = "2"
	3__ResellerSalesPriceObjectType ResellerSalesPriceObjectType = "3"
	4__ResellerSalesPriceObjectType ResellerSalesPriceObjectType = "4"
	5__ResellerSalesPriceObjectType ResellerSalesPriceObjectType = "5"
)
