/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Price struct {
	Value float64 `json:"value,omitempty"`
	CurrencyCode string `json:"currencyCode,omitempty"`
}
