/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AwsMasterAccountStatus int32

// List of AwsMasterAccountStatus
const (
	0__AwsMasterAccountStatus AwsMasterAccountStatus = "0"
	1__AwsMasterAccountStatus AwsMasterAccountStatus = "1"
	2__AwsMasterAccountStatus AwsMasterAccountStatus = "2"
	3__AwsMasterAccountStatus AwsMasterAccountStatus = "3"
)
