/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResellerSalesPricePriceType int32

// List of ResellerSalesPricePriceType
const (
	1__ResellerSalesPricePriceType ResellerSalesPricePriceType = "1"
	2__ResellerSalesPricePriceType ResellerSalesPricePriceType = "2"
	3__ResellerSalesPricePriceType ResellerSalesPricePriceType = "3"
)
