/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ServiceAccountAgreement struct {
	FirstName string `json:"firstName,omitempty"`
	LastName string `json:"lastName,omitempty"`
	PhoneNumber string `json:"phoneNumber,omitempty"`
	Email string `json:"email,omitempty"`
	DateAgreed time.Time `json:"dateAgreed,omitempty"`
	AgreementType *AgreementTypeConsent `json:"agreementType,omitempty"`
}
