/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AgreementReportStatus int32

// List of AgreementReportStatus
const (
	0__AgreementReportStatus AgreementReportStatus = "0"
	1__AgreementReportStatus AgreementReportStatus = "1"
	2__AgreementReportStatus AgreementReportStatus = "2"
	4__AgreementReportStatus AgreementReportStatus = "4"
	6__AgreementReportStatus AgreementReportStatus = "6"
)
