/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BillingCycleEnum int32

// List of BillingCycleEnum
const (
	0__BillingCycleEnum BillingCycleEnum = "0"
	1__BillingCycleEnum BillingCycleEnum = "1"
	2__BillingCycleEnum BillingCycleEnum = "2"
	3__BillingCycleEnum BillingCycleEnum = "3"
	4__BillingCycleEnum BillingCycleEnum = "4"
	5__BillingCycleEnum BillingCycleEnum = "5"
	7__BillingCycleEnum BillingCycleEnum = "7"
	8__BillingCycleEnum BillingCycleEnum = "8"
	9__BillingCycleEnum BillingCycleEnum = "9"
)
