/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Consumer struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Organization *ObjectReference `json:"organization,omitempty"`
}
