/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ScheduledNextTermInstructions struct {
	Product *Product `json:"product,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
}
