/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SubscriptionTransition struct {
	ToCatalogItemId string `json:"toCatalogItemId,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	TransitionType string `json:"transitionType,omitempty"`
	BillingCycle *BillingCycleEnum `json:"billingCycle,omitempty"`
	Term string `json:"term,omitempty"`
}
