/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EntityStatus int32

// List of EntityStatus
const (
	0__EntityStatus EntityStatus = "0"
	1__EntityStatus EntityStatus = "1"
)
