/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Event struct {
	Name string `json:"name,omitempty"`
	TimeStamp time.Time `json:"timeStamp,omitempty"`
	Status string `json:"status,omitempty"`
}
