/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SubscriptionSortBy int32

// List of SubscriptionSortBy
const (
	0__SubscriptionSortBy SubscriptionSortBy = "0"
	1__SubscriptionSortBy SubscriptionSortBy = "1"
	2__SubscriptionSortBy SubscriptionSortBy = "2"
	3__SubscriptionSortBy SubscriptionSortBy = "3"
)
