/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AssetStatus int32

// List of AssetStatus
const (
	0__AssetStatus AssetStatus = "0"
	1__AssetStatus AssetStatus = "1"
	2__AssetStatus AssetStatus = "2"
	4__AssetStatus AssetStatus = "4"
	8__AssetStatus AssetStatus = "8"
	15__AssetStatus AssetStatus = "15"
)
