/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Agreement struct {
	Id int32 `json:"id,omitempty"`
	Organization *ObjectReference `json:"organization,omitempty"`
	Name string `json:"name,omitempty"`
	SalesPriceCurrencyCode string `json:"salesPriceCurrencyCode,omitempty"`
	StartDate time.Time `json:"startDate,omitempty"`
	EndDate time.Time `json:"endDate,omitempty"`
	Disabled bool `json:"disabled,omitempty"`
	Publisher *ObjectReference `json:"publisher,omitempty"`
	Program *ObjectReference `json:"program,omitempty"`
	Number string `json:"number,omitempty"`
	CustomerNumber string `json:"customerNumber,omitempty"`
	MasterAgreement string `json:"masterAgreement,omitempty"`
	HasTerms bool `json:"hasTerms,omitempty"`
	AgreementType *AgreementType `json:"agreementType,omitempty"`
	ParentAgreementId int32 `json:"parentAgreementId,omitempty"`
	CommitmentLevel float64 `json:"commitmentLevel,omitempty"`
	ConsumerId int32 `json:"consumerId,omitempty"`
}
