/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AssetOrderLineError struct {
	ReasonCode string `json:"reasonCode,omitempty"`
	Description string `json:"description,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
}
