/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ProductContainer struct {
	Id int32 `json:"id,omitempty"`
	OrderListId int32 `json:"orderListId,omitempty"`
	Note string `json:"note,omitempty"`
	UsageMonth time.Time `json:"usageMonth,omitempty"`
	Name string `json:"name,omitempty"`
	ActiveDraft bool `json:"activeDraft,omitempty"`
	Removed bool `json:"removed,omitempty"`
	CreatedByUserId string `json:"createdByUserId,omitempty"`
	AxContactUserId string `json:"axContactUserId,omitempty"`
	CreatedDate time.Time `json:"createdDate,omitempty"`
	OrderStatusChangedDate time.Time `json:"orderStatusChangedDate,omitempty"`
	ContactUser *UserProfile `json:"contactUser,omitempty"`
	Organization *ObjectReference `json:"organization,omitempty"`
	Publisher *ObjectReference `json:"publisher,omitempty"`
	Program *Program `json:"program,omitempty"`
	ProductRows []ProductRow `json:"productRows,omitempty"`
	Comments []ProductContainerComment `json:"comments,omitempty"`
	InvoiceProfile *InvoiceProfile `json:"invoiceProfile,omitempty"`
	DeliveryAddress *AddressData `json:"deliveryAddress,omitempty"`
	InvoiceAddress *AddressData `json:"invoiceAddress,omitempty"`
	Type_ *ProductContainerType `json:"type,omitempty"`
	Category *ProductContainerCategory `json:"category,omitempty"`
	QuoteValidToDate time.Time `json:"quoteValidToDate,omitempty"`
	TotalSalesPrice []Price `json:"totalSalesPrice,omitempty"`
	TotalAlternativeSalesPrice []Price `json:"totalAlternativeSalesPrice,omitempty"`
	Issues []ProductContainerIssue `json:"issues,omitempty"`
	SubmittedBy *ProductContainerCommentUser `json:"submittedBy,omitempty"`
	Sent time.Time `json:"sent,omitempty"`
	InvoiceReference string `json:"invoiceReference,omitempty"`
	OrderReference string `json:"orderReference,omitempty"`
	Requisition string `json:"requisition,omitempty"`
}
