/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AgreementReport struct {
	ProductContainer *ObjectReferenceDto `json:"productContainer,omitempty"`
	Agreement *AgreementIdentityReferenceDto `json:"agreement,omitempty"`
	Status *AgreementReportStatus `json:"status,omitempty"`
	HasValidAgreementTerm bool `json:"hasValidAgreementTerm,omitempty"`
}
