/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AssetOrderLine struct {
	ProductId string `json:"productId,omitempty"`
	SubscriptionId int32 `json:"subscriptionId,omitempty"`
	ArmRegionName string `json:"armRegionName,omitempty"`
	SkuId string `json:"skuId,omitempty"`
	ProductVariantId int32 `json:"productVariantId,omitempty"`
	Quantity int32 `json:"quantity,omitempty"`
	BillingCycle *BillingCycleType `json:"billingCycle,omitempty"`
	ProvisioningContext map[string]string `json:"provisioningContext,omitempty"`
	Type_ *AssetType `json:"type,omitempty"`
	RequiresInventoryCheck bool `json:"requiresInventoryCheck,omitempty"`
	CatalogItemId string `json:"catalogItemId,omitempty"`
	TermDuration string `json:"termDuration,omitempty"`
	Scope *AssetScope `json:"scope,omitempty"`
	ResellerPriceType *SalesPriceType `json:"resellerPriceType,omitempty"`
	ResellerPriceTypeValue float64 `json:"resellerPriceTypeValue,omitempty"`
	IsTrial bool `json:"isTrial,omitempty"`
	Name string `json:"name,omitempty"`
	AttestationAccepted bool `json:"attestationAccepted,omitempty"`
	Tags *AssetTags `json:"tags,omitempty"`
	Errors []AssetOrderLineError `json:"errors,omitempty"`
}
