/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Secret struct {
	Id int32 `json:"id,omitempty"`
	ClientId string `json:"clientId,omitempty"`
	Value string `json:"value,omitempty"`
	Description string `json:"description,omitempty"`
	Expiration time.Time `json:"expiration,omitempty"`
	TimeStamp time.Time `json:"timeStamp,omitempty"`
}
