/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddressData struct {
	AxAddressId int64 `json:"axAddressId,omitempty"`
	Name string `json:"name,omitempty"`
	CompleteAddress string `json:"completeAddress,omitempty"`
	Street string `json:"street,omitempty"`
	ZipCode string `json:"zipCode,omitempty"`
	City string `json:"city,omitempty"`
	County string `json:"county,omitempty"`
	State string `json:"state,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
}
