/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProgramType int32

// List of ProgramType
const (
	0__ProgramType ProgramType = "0"
	1__ProgramType ProgramType = "1"
	2__ProgramType ProgramType = "2"
	4__ProgramType ProgramType = "4"
)
