/*
 * Crayon Group Customer API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserRole int32

// List of UserRole
const (
	0__UserRole UserRole = "0"
	1__UserRole UserRole = "1"
	2__UserRole UserRole = "2"
)
